[workspace]
members = [
    "lotus_scrape",
    "lotus_web",
]

[package]
name = "lotus"
version = "0.3.0"
edition = "2021"
authors = ["William Patmore <wapatmore@gmail.com>"]

[dependencies]
const_format = "0.2.33"
lazy_static = "1.5.0"
