[package]
name = "scp-recommender"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
http = "1.1.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.19.1"
tokio = { version = "1.38.1", features = ["full"] }
